// ui/src/apps/notepad/index.vue
<template>
  <div class="flex h-full min-h-0 flex-col" :style="bgStyle">
    <div class="m-3 rounded-[14px] px-3 py-2" :style="panelStyle">
      <textarea
        v-model="draft"
        rows="4"
        class="min-h-[86px] w-full resize-none border-0 bg-transparent text-[14px] leading-relaxed text-[#3a2415] outline-none placeholder:text-[#9a8060]"
        placeholder="写点什么..."
      />
      <div class="mt-2 flex items-center gap-2">
        <button
          class="rounded-[10px] px-3 py-1.5 text-[12px] font-bold text-[#3a2415] active:translate-y-[1px]"
          :style="buttonStyle"
          :disabled="!draft.trim()"
          @click="save"
        >保存</button>
        <span class="text-[11px] text-[#9a8060]">智能润色由任务能力处理</span>
      </div>
    </div>

    <div class="min-h-0 flex-1 overflow-y-auto px-3 pb-5 [scrollbar-width:none]">
      <div v-if="!notes.length" class="py-16 text-center text-[13px] text-[#a09080]">还没有笔记</div>
      <div v-else class="flex flex-col gap-2">
        <article v-for="note in notes" :key="note.id" class="rounded-[14px] px-3.5 py-3" :style="panelStyle">
          <div class="whitespace-pre-wrap text-[13.5px] leading-relaxed text-[#3a2415]">{{ note.content || note.title }}</div>
          <div class="mt-2 flex items-center gap-2 border-t border-[rgba(120,90,40,0.10)] pt-2">
            <span class="flex-1 font-sans text-[10.5px] text-[#a08a68]">{{ note.updated_at || note.created_at }}</span>
            <button class="text-[11px] font-bold text-[#9a3a2a]" @click="remove(note.id)">删除</button>
          </div>
        </article>
      </div>
    </div>
  </div>
</template>

<script setup>
import { onMounted, ref } from 'vue';

const notes = ref([]);
const draft = ref('');

const request = async (url, options = {}) => {
  const res = await fetch(url, options);
  const data = await res.json().catch(() => ({}));
  if (!res.ok || data.ok === false) throw new Error(data.error || `HTTP ${res.status}`);
  return data;
};

const load = async () => {
  const data = await request('/apps/notepad/notes');
  notes.value = data.notes || [];
};

const save = async () => {
  const content = draft.value.trim();
  if (!content) return;
  await request('/apps/notepad/notes', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ title: content.slice(0, 24), content }),
  });
  draft.value = '';
  await load();
};

const remove = async (id) => {
  await request(`/apps/notepad/notes?id=${encodeURIComponent(id)}`, { method: 'DELETE' });
  await load();
};

onMounted(load);

const bgStyle = {
  background: 'linear-gradient(180deg,#f0e8d5 0%,#e8dfca 100%)',
};
const panelStyle = {
  background: 'linear-gradient(160deg,#faf5e8 0%,#f2ebd8 100%)',
  boxShadow: '0 2px 8px rgba(90,60,20,0.1),inset 0 1px 0 rgba(255,255,255,0.8)',
  border: '1px solid rgba(180,150,80,0.18)',
};
const buttonStyle = {
  background: 'linear-gradient(180deg,#d4981e 0%,#a07010 100%)',
  boxShadow: '0 3px 0 #6a4800,0 4px 10px rgba(0,0,0,0.18),inset 0 1px 0 rgba(255,215,80,0.35)',
  color: 'rgba(255,245,190,0.95)',
};
</script>

// ui/src/apps/notepad/index.tsx
import { useEffect, useState } from "react";
import { Check, Pencil, Trash2, X } from "lucide-react";
import { appFetch } from "../lib";

type Note = {
  id: number;
  title: string;
  content: string;
  created_at: string;
  updated_at: string;
};

const BASE = "/apps/notepad/notes";

const formatTime = (value?: string) => {
  if (!value) return "";
  const date = new Date(value.includes("T") ? value : value.replace(" ", "T") + "Z");
  return Number.isNaN(date.getTime()) ? value : date.toLocaleString();
};

export default function NotepadApp() {
  const [notes, setNotes] = useState<Note[]>([]);
  const [draft, setDraft] = useState("");
  const [editingId, setEditingId] = useState<number | null>(null);
  const [editText, setEditText] = useState("");
  const [error, setError] = useState("");

  const refresh = async () => {
    try {
      const { notes: list } = await appFetch<{ notes: Note[] }>(BASE);
      setNotes(list);
    } catch (e) {
      setError(e instanceof Error ? e.message : "加载失败");
    }
  };

  useEffect(() => {
    refresh();
  }, []);

  const create = async () => {
    const content = draft.trim();
    if (!content) return;
    try {
      await appFetch(BASE, { method: "POST", body: JSON.stringify({ title: "", content }) });
      setDraft("");
      await refresh();
    } catch (e) {
      setError(e instanceof Error ? e.message : "记录失败");
    }
  };

  const saveEdit = async (id: number) => {
    try {
      await appFetch(`${BASE}?id=${id}`, { method: "PATCH", body: JSON.stringify({ content: editText }) });
      setEditingId(null);
      await refresh();
    } catch (e) {
      setError(e instanceof Error ? e.message : "保存失败");
    }
  };

  const remove = async (id: number) => {
    try {
      await appFetch(`${BASE}?id=${id}`, { method: "DELETE" });
      if (editingId === id) setEditingId(null);
      await refresh();
    } catch (e) {
      setError(e instanceof Error ? e.message : "删除失败");
    }
  };

  return (
    <div className="flex-1 min-h-0 overflow-y-auto">
      <div className="mx-auto max-w-2xl px-5 py-8 flex flex-col gap-5">
        <h2 className="m-0 text-2xl font-semibold text-text leading-tight">记事本</h2>

        {/* 顶部输入框 */}
        <div className="flex flex-col gap-2 p-3 rounded-2xl border border-border-soft bg-bg-raised focus-within:border-accent transition-colors">
          <textarea
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            onKeyDown={(e) => {
              if ((e.metaKey || e.ctrlKey) && e.key === "Enter") create();
            }}
            className="w-full resize-none bg-transparent text-text text-sm leading-relaxed outline-none min-h-[72px]"
            placeholder="现在的想法是…(⌘/Ctrl + Enter 记录)"
          />
          <div className="flex items-center justify-between">
            <span className="text-xxs text-text-faint">{draft.trim().length} 字</span>
            <button className="btn btn-sm btn-primary" disabled={!draft.trim()} onClick={create}>
              记录
            </button>
          </div>
        </div>

        {error ? <p className="inline-error">{error}</p> : null}

        {/* 笔记流 */}
        <div className="flex flex-col gap-3">
          {notes.map((note) => (
            <div key={note.id} className="group flex flex-col gap-2 p-4 rounded-2xl border border-border-soft bg-bg-raised">
              <div className="flex items-center justify-between gap-2">
                <span className="text-xxs text-text-faint">{formatTime(note.updated_at)}</span>
                <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                  {editingId === note.id ? (
                    <>
                      <button className="btn btn-sm btn-ghost !px-2 !h-7 !w-7" title="保存" onClick={() => saveEdit(note.id)}>
                        <Check size={14} />
                      </button>
                      <button className="btn btn-sm btn-ghost !px-2 !h-7 !w-7" title="取消" onClick={() => setEditingId(null)}>
                        <X size={14} />
                      </button>
                    </>
                  ) : (
                    <>
                      <button
                        className="btn btn-sm btn-ghost !px-2 !h-7 !w-7"
                        title="编辑"
                        onClick={() => {
                          setEditingId(note.id);
                          setEditText(note.content);
                        }}
                      >
                        <Pencil size={13} />
                      </button>
                      <button className="btn btn-sm btn-ghost !px-2 !h-7 !w-7" title="删除" onClick={() => remove(note.id)}>
                        <Trash2 size={13} />
                      </button>
                    </>
                  )}
                </div>
              </div>
              {editingId === note.id ? (
                <textarea
                  value={editText}
                  onChange={(e) => setEditText(e.target.value)}
                  className="w-full resize-none bg-transparent text-text text-sm leading-relaxed outline-none min-h-[80px] border border-border-soft rounded-lg p-2"
                  autoFocus
                />
              ) : (
                <p className="m-0 text-sm text-text leading-relaxed whitespace-pre-wrap break-words">{note.content}</p>
              )}
            </div>
          ))}
          {notes.length === 0 ? (
            <div className="empty mt-2">
              <div className="text-text-dim font-medium">还没有记录</div>
              <div className="text-xxs text-text-faint">在上方写下第一条</div>
            </div>
          ) : null}
        </div>
      </div>
    </div>
  );
}
