// gui/src/apps/ledger/index.tsx
import { useEffect, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { appFetch } from "../lib";

type Entry = {
  id: number;
  type: "income" | "expense";
  amount: number;
  category: string;
  note: string;
  occurred_on: string;
};
type Summary = { income: number; expense: number; balance: number };

const BASE = "/apps/ledger/entries";
const yuan = (n: number) => `¥${n.toFixed(2)}`;

export default function LedgerApp() {
  const [entries, setEntries] = useState<Entry[]>([]);
  const [summary, setSummary] = useState<Summary>({ income: 0, expense: 0, balance: 0 });
  const [form, setForm] = useState({ type: "expense" as "income" | "expense", amount: "", category: "", note: "" });
  const [error, setError] = useState("");

  const refresh = async () => {
    try {
      const data = await appFetch<{ entries: Entry[]; summary: Summary }>(BASE);
      setEntries(data.entries);
      setSummary(data.summary);
    } catch (e) {
      setError(e instanceof Error ? e.message : "加载失败");
    }
  };

  useEffect(() => {
    refresh();
  }, []);

  const add = async () => {
    const amount = Number(form.amount);
    if (!amount || amount <= 0) {
      setError("请输入有效金额");
      return;
    }
    try {
      await appFetch(BASE, {
        method: "POST",
        body: JSON.stringify({ type: form.type, amount, category: form.category.trim(), note: form.note.trim() }),
      });
      setForm({ type: form.type, amount: "", category: "", note: "" });
      setError("");
      await refresh();
    } catch (e) {
      setError(e instanceof Error ? e.message : "记账失败");
    }
  };

  const remove = async (id: number) => {
    try {
      await appFetch(`${BASE}?id=${id}`, { method: "DELETE" });
      await refresh();
    } catch (e) {
      setError(e instanceof Error ? e.message : "删除失败");
    }
  };

  return (
    <div className="flex-1 min-h-0 overflow-y-auto">
      <div className="mx-auto max-w-2xl px-5 py-8 flex flex-col gap-5">
        <h2 className="m-0 text-2xl font-semibold text-text leading-tight">记账本</h2>

        {/* 汇总 */}
        <div className="grid grid-cols-3 gap-3">
          <SummaryCard label="收入" value={yuan(summary.income)} tone="text-emerald-500" />
          <SummaryCard label="支出" value={yuan(summary.expense)} tone="text-rose-500" />
          <SummaryCard label="结余" value={yuan(summary.balance)} tone={summary.balance >= 0 ? "text-text" : "text-rose-500"} />
        </div>

        {error ? <p className="inline-error">{error}</p> : null}

        {/* 记一笔 */}
        <div className="flex flex-col gap-3 p-4 rounded-2xl border border-border-soft bg-bg-raised">
          <div className="flex gap-1 p-1 rounded-xl bg-bg-hover w-fit">
            {(["expense", "income"] as const).map((t) => (
              <button
                key={t}
                className={[
                  "px-3 py-1 rounded-lg text-sm font-medium transition-colors",
                  form.type === t ? "bg-bg-raised text-text shadow-sm" : "text-text-mute",
                ].join(" ")}
                onClick={() => setForm({ ...form, type: t })}
              >
                {t === "expense" ? "支出" : "收入"}
              </button>
            ))}
          </div>
          <div className="flex gap-2 flex-wrap">
            <input
              value={form.amount}
              onChange={(e) => setForm({ ...form, amount: e.target.value })}
              className="input w-28"
              type="number"
              placeholder="金额"
            />
            <input
              value={form.category}
              onChange={(e) => setForm({ ...form, category: e.target.value })}
              className="input w-28"
              placeholder="分类"
            />
            <input
              value={form.note}
              onChange={(e) => setForm({ ...form, note: e.target.value })}
              onKeyDown={(e) => e.key === "Enter" && add()}
              className="input flex-1 min-w-[120px]"
              placeholder="备注"
            />
            <button className="btn btn-sm btn-primary" onClick={add}>
              <Plus size={14} />
              记一笔
            </button>
          </div>
        </div>

        {/* 流水 */}
        <div className="flex flex-col gap-1.5">
          {entries.map((entry) => (
            <div
              key={entry.id}
              className="flex items-center gap-3 p-3 rounded-xl border border-border-soft bg-bg-raised group"
            >
              <div className="flex flex-col min-w-0 flex-1">
                <span className="text-sm text-text truncate">
                  {entry.category || "未分类"}
                  {entry.note ? <span className="text-text-mute"> · {entry.note}</span> : null}
                </span>
                <span className="text-xxs text-text-faint">{entry.occurred_on}</span>
              </div>
              <span className={["text-sm font-semibold shrink-0", entry.type === "income" ? "text-emerald-500" : "text-rose-500"].join(" ")}>
                {entry.type === "income" ? "+" : "-"}
                {yuan(entry.amount)}
              </span>
              <button
                className="btn btn-sm btn-ghost !px-2 opacity-0 group-hover:opacity-100 transition-opacity"
                title="删除"
                onClick={() => remove(entry.id)}
              >
                <Trash2 size={14} />
              </button>
            </div>
          ))}
          {entries.length === 0 ? (
            <div className="empty mt-2">
              <div className="text-text-dim font-medium">还没有账目</div>
              <div className="text-xxs text-text-faint">上方记第一笔</div>
            </div>
          ) : null}
        </div>
      </div>
    </div>
  );
}

function SummaryCard({ label, value, tone }: { label: string; value: string; tone: string }) {
  return (
    <div className="flex flex-col gap-1 p-3 rounded-2xl border border-border-soft bg-bg-raised">
      <span className="text-xxs text-text-faint">{label}</span>
      <span className={["text-lg font-semibold truncate", tone].join(" ")}>{value}</span>
    </div>
  );
}

// ui/src/apps/ledger/index.vue
<template>
  <div class="flex h-full min-h-0 flex-col" :style="bgStyle">
    <div class="m-3 rounded-[14px] px-4 py-3" :style="coverStyle">
      <div class="font-mono text-[10px] uppercase tracking-[3px] text-[rgba(255,235,180,0.55)]">BALANCE · 余额</div>
      <div class="mt-1 font-mono text-[28px] font-extrabold leading-none tabular-nums" :style="{ color: summary.balance >= 0 ? '#a8e890' : '#ff9080' }">
        ¥ {{ fmt(summary.balance) }}
      </div>
      <div class="mt-2 flex items-center gap-3 border-t border-[rgba(255,235,180,0.15)] pt-1.5 font-mono text-[10.5px]">
        <span class="text-[#a8e890]">收入 ¥{{ fmt(summary.income) }}</span>
        <span class="text-[rgba(255,235,180,0.30)]">/</span>
        <span class="text-[#ff9080]">支出 ¥{{ fmt(summary.expense) }}</span>
      </div>
    </div>

    <div class="mx-3 mb-2 rounded-[14px] px-3 py-2" :style="panelStyle">
      <div class="mb-2 flex rounded-[9px] bg-[rgba(120,90,40,0.10)] p-0.5 text-[12px] font-bold">
        <button class="flex-1 rounded-[7px] py-1" :class="form.type === 'expense' ? 'bg-[#a8483a] text-white' : 'text-[#7a3a2a]'" @click="form.type = 'expense'">支出</button>
        <button class="flex-1 rounded-[7px] py-1" :class="form.type === 'income' ? 'bg-[#3a7a3a] text-white' : 'text-[#3a5a3a]'" @click="form.type = 'income'">收入</button>
      </div>
      <div class="grid grid-cols-[1fr_96px] gap-2">
        <input v-model="form.category" class="rounded-[9px] border border-[rgba(120,90,40,0.18)] bg-white/70 px-2.5 py-1.5 text-[13px] outline-none" placeholder="分类" />
        <input v-model.number="form.amount" type="number" inputmode="decimal" class="rounded-[9px] border border-[rgba(120,90,40,0.18)] bg-white/70 px-2.5 py-1.5 text-right font-mono text-[13px] outline-none" placeholder="金额" />
      </div>
      <div class="mt-2 flex items-center gap-2">
        <input v-model="form.note" class="min-w-0 flex-1 rounded-[9px] border border-[rgba(120,90,40,0.18)] bg-white/70 px-2.5 py-1.5 text-[13px] outline-none" placeholder="备注" @keyup.enter="add" />
        <button class="rounded-[9px] px-3 py-1.5 text-[12px] font-bold" :style="buttonStyle" :disabled="!form.amount" @click="add">记录</button>
      </div>
      <div class="mt-1 text-[11px] text-[#9a8060]">智能输入由任务能力处理</div>
    </div>

    <div class="min-h-0 flex-1 overflow-y-auto px-3 pb-5 [scrollbar-width:none]">
      <div v-if="!entries.length" class="py-16 text-center text-[13px] text-[#a09080]">还没有账目</div>
      <div v-else class="flex flex-col gap-2">
        <div v-for="entry in entries" :key="entry.id" class="flex items-center gap-3 rounded-[14px] px-3.5 py-3" :style="panelStyle">
          <span class="w-1 self-stretch rounded-full" :class="entry.type === 'income' ? 'bg-[#3a7a3a]' : 'bg-[#a83a28]'"></span>
          <div class="min-w-0 flex-1">
            <div class="truncate text-[13.5px] font-bold text-[#3a2415]">{{ entry.category || (entry.type === 'income' ? '收入' : '支出') }}</div>
            <div class="truncate text-[10.5px] text-[#8a7058]">{{ entry.note || entry.occurred_on }}</div>
          </div>
          <div class="font-mono text-[14px] font-bold tabular-nums" :class="entry.type === 'income' ? 'text-[#287a38]' : 'text-[#a83020]'">
            {{ entry.type === 'income' ? '+' : '-' }}¥{{ fmt(entry.amount) }}
          </div>
          <button class="text-[11px] font-bold text-[#9a3a2a]" @click="remove(entry.id)">删</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue';

const entries = ref([]);
const summary = ref({ income: 0, expense: 0, balance: 0 });
const form = reactive({ type: 'expense', amount: '', category: '', note: '' });

const fmt = (n) => Number(n || 0).toLocaleString('zh-CN', { maximumFractionDigits: 2 });

const request = async (url, options = {}) => {
  const res = await fetch(url, options);
  const data = await res.json().catch(() => ({}));
  if (!res.ok || data.ok === false) throw new Error(data.error || `HTTP ${res.status}`);
  return data;
};

const load = async () => {
  const data = await request('/apps/ledger/entries');
  entries.value = data.entries || [];
  summary.value = data.summary || { income: 0, expense: 0, balance: 0 };
};

const add = async () => {
  if (!form.amount) return;
  await request('/apps/ledger/entries', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(form),
  });
  form.amount = '';
  form.category = '';
  form.note = '';
  await load();
};

const remove = async (id) => {
  await request(`/apps/ledger/entries?id=${encodeURIComponent(id)}`, { method: 'DELETE' });
  await load();
};

onMounted(load);

const bgStyle = {
  background: 'linear-gradient(180deg,#f0e8d5 0%,#e8dfca 100%)',
};
const coverStyle = {
  background: 'linear-gradient(160deg,#244225 0%,#102414 100%)',
  boxShadow: '0 4px 14px rgba(30,60,30,0.25),inset 0 1px 0 rgba(255,255,255,0.18)',
  border: '1px solid rgba(50,90,60,0.25)',
};
const panelStyle = {
  background: 'linear-gradient(160deg,#faf5e8 0%,#f2ebd8 100%)',
  boxShadow: '0 2px 8px rgba(90,60,20,0.1),inset 0 1px 0 rgba(255,255,255,0.8)',
  border: '1px solid rgba(180,150,80,0.18)',
};
const buttonStyle = {
  background: 'linear-gradient(180deg,#d4981e 0%,#a07010 100%)',
  boxShadow: '0 3px 0 #6a4800,0 4px 10px rgba(0,0,0,0.18),inset 0 1px 0 rgba(255,215,80,0.35)',
  color: 'rgba(255,245,190,0.95)',
};
</script>
